# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jingze Liu
title: Master of Deep Learning
email: sonnyliu98@outlook.com
# website: https://github.com/sonnylau98

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: JingzeLiu11
github_username:  sonnylau98
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs

  Hi! My name's Jingze and I'm a postgraduate student in Shanghai University. My study is focus on applying Mathematics in <mark>Computer Vision</mark> Based on Deep Learning, including Image Restoration and segmentation. I also participated in the MIT blended learning program, where I tackled <mark>Atom Simulation</mark> problems using machine learning methods and explored the use of <mark>Quantum Computing</mark> to speed up the topology data analysis process.
  
  Plus, I enjoy:
  - cryptography
  - game theory
  - fundamental mathematics.

  I am a person who is good at self-reflection, has a pioneering spirit, and enjoys communicating with others.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NISQ_QTDA
        link: github.com/sonnylau98
        # link_text: Project Website
        additional_links:
          - title:  github.com/sonnylau98/NISQ_QTDA
            icon: fab fa-github
            url: github.com/sonnylau98/NISQ_QTDA
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The project is still ongoing.
        description: | # this will include new lines to allow paragraphs
          Topological Data Analysis (TDA) can be applied in various fields, such as biology, neuroscience, engineering, and social sciences. However, its classical methods have exponential time complexity, making it computationally expensive for large datasets. To address this issue, many researchers have proposed quantum algorithms for accelerating TDA's speed. While the implementation of speed-up algorithms in coding is still ongoing, I have attempted to achieve this goal using the qiskit package in Python. Specifically, I have implemented some methods, such as moment estimation and Chebyshev polynomial, in NISQ-QTDA (Ubaru et al., 2021).

  - layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stars Crawler from Baidu
        link: github.com/sonnylau98
        # link_text: Project Website
        additional_links:
          - title:  github.com/sonnylau98/stars-crawler-baidu
            icon: fab fa-github
            url: github.com/sonnylau98/stars-crawler-baidu
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A fun way to help friends around us who enjoy gossip.
        description: | # this will include new lines to allow paragraphs
          This is an entertainment project that involves using Python to crawl information on celebrity stars and their relationships from Baidu Baike, a popular Chinese online encyclopedia. The project then automatically generates a network graph to visualize the relationships between the celebrities.
          
#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Biomedical and Bio-informatics
        caption: https://arxiv.org/ftp/arxiv/papers/2204/2204.11026.pdf
        sub_title: Bsc in Mathematics
        quote: >
          Bioinformatic analysis for structure and function of Glutamine synthetase (GS) from Antarctic sea ice bacterium Pseudoalteromonas sp. M175
        description: | # this will include new lines to allow paragraphs
          - Object: To predict structure and function of Glutamine synthetase (GS) from Pseudoalteromonas sp. by bioinformatics technology, and to provide a theoretical basis for further study.
          - Methods: Open reading frame (ORF) of GS sequence from Pseudoalteromonas sp. was obtained by ORF finder and was translated into amino acid residue. The structure domain was analyzed by Blast. 
          - Tools: Protparam, ProtScale, SignalP-4.0, TMHMM, SOPMA, SWISS-MODEL, NCBI SMART-BLAST and MAGA 7.0, the structure and function of the protein were predicted and analyzed.
          - Results: The results showed that the sequence was GS with 468 amino acid residues, theoretical molecular weight was 51986.64 Da. The protein has the closest evolutionary status with Shewanella oneidensis. Then it had no signal peptide site and transmembrane domain. Secondary structure of GS contained 35.04% α-helix, 16.67% Extended chain, 5.34% β-turn, 42.95% RandomCoil.
          - Conclusions: This GU was a variety of biological functions of protein that may be used as a molecular samples of microbial nitrogen metabolism in extreme environments.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Qingdao University
        caption: 2019 - 2023
        sub_title: Bsc in Mathematics
        quote: >
          Qingdao University is a public comprehensive university located in Qingdao, China. It offers diverse programs in 26 schools, covering engineering, science, management, law, medicine, and liberal arts. 
        description: | # this will include new lines to allow paragraphs
          - Undergraduate achievement ranks in the top 5% of the grade, with algebra, mathematical analysis, topology, and other subjects ranking first in the grade.
          - Awarded six academic scholarships
          - Selected as an outstanding student during my undergraduate studies

  - layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shanghai University
        caption: 2023 - 
        sub_title: MPhil in Deep Learning
        quote: >
          Established in 1922, SHU is a public research university in Shanghai, China. It's recognized for its strengths in engineering, science, and business disciplines and has partnerships with over 200 universities and research institutions worldwide.
        description: | # this will include new lines to allow paragraphs
          Recommended by Qingdao University for entering Shanghai University without examination to pursue a funded Mphil degree.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Simple game development
      - 3D modeling for art purposes
      - Calisthenics
      - Photography
      - Film
      - Other tricks like timbre cloning based on deep learning

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
