# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jingze Liu
#title: Postgraduate in Deep Learning
email: sonnyliu98@outlook.com
phone: (+86)13361223604
# website: https://github.com/sonnylau98

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: JingzeLiu11
github_username:  sonnylau98
facebook_username: liu.sonny.5
instagram_username: sonnylau8

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  My name’s Jingze and I’m a postgraduate student in Shanghai University. My study is focus on applying Mathematics in <mark>Computer Vision</mark> Based on <mark>Deep Learning</mark>, including Image Restoration and segmentation. I also participated in the MIT blended learning program, where I tackled Atom Simulation problems using <mark>Machine Learning</mark> methods and explored the use of Quantum Computing to speed up the topology data analysis process.
  
  Plus, I enjoy:
  - programming
  - fundamental mathematics

  I am a person who is good at self-reflection, has a pioneering spirit, and enjoys communicating with others.
          
#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sequence analysis and homology modeling of glutamine synthetase (GS)
        link: https://api.semanticscholar.org/CorpusID:248377217
 #       picture: images/GS.jpg
 #       img_style: project-img
        quote: >
          Bioinformatic analysis for structure and function of Glutamine synthetase(GS) in Pseudomonas alternata sp. 
          (Published by The ICBB 2022 Conference on Bio-informatics) 
        description: | # this will include new lines to allow paragraphs
          This study used homology modeling to study the structure and molecular evolution of glutamine synthetase from Antarctic sea ice bacteria, optimized the modeling results by thermodynamic simulation, and improved the modeling accuracy by 2.7%. In addition, the secondary structure and physical and chemical characteristics are also concerned by this study.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Qingdao University
        caption: 2019 - 2023
        sub_title: Bsc in Mathematics
        quote: >
          Major GPA: 3.85/4
        description: | # this will include new lines to allow paragraphs
          - Undergraduate achievement ranks in the top 5% of the grade, with algebra, mathematical analysis, topology, and other subjects ranking first in the grade.
          - Awarded six academic scholarships
          - Selected as an outstanding student during my undergraduate studies

  - layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shanghai University
        caption: 2023 - 
        sub_title: Postgraduate in Deep Learning
        quote: >
          Advisor：Yaxin Peng
          
          Research Group：Cross-Modality Medical Image Segmentation
          
        description: | # this will include new lines to allow paragraphs
          Recommended by Qingdao University for entering Shanghai University without examination to pursue a funded Mphil degree.
          
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NISQ_QTDA
        link: github.com/sonnylau98
          # link_text: Project Website
        additional_links:
          - title:  github.com/sonnylau98/NISQ_QTDA
            icon: fab fa-github
            url: github.com/sonnylau98/NISQ_QTDA
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The project is still ongoing.
        description: | # this will include new lines to allow paragraphs
          Topological Data Analysis (TDA) can be applied in various fields, such as biology, neuroscience, engineering, and social sciences. However, its classical methods have <mark>exponential</mark> time complexity, making it computationally expensive for large datasets. To address this issue, many researchers have proposed quantum algorithms for <mark>accelerating</mark> TDA's speed. While the implementation of speed-up algorithms in coding is still ongoing, I have attempted to achieve this goal using the qiskit package in Python. Specifically, I have implemented some methods, such as moment estimation and Chebyshev polynomial, in NISQ-QTDA (Ubaru et al., 2021).

  - layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stars Crawler from Baidu
        link: github.com/sonnylau98
        # link_text: Project Website
        additional_links:
          - title:  github.com/sonnylau98/stars-crawler-baidu
            icon: fab fa-github
            url: github.com/sonnylau98/stars-crawler-baidu
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A fun way to help friends around us who enjoy gossip.
        description: | # this will include new lines to allow paragraphs
          This is an entertainment project that involves using Python to crawl information on celebrity stars and their relationships from Baidu Baike, a popular Chinese online encyclopedia. The project then automatically generates a network graph to visualize the relationships between the celebrities.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Simple game development
      - 3D modeling for art purposes
      - Calisthenics
      - Other tricks like timbre cloning based on deep learning

  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
